export const colors = {
  bg: "#f4f6f8",
  card: "#ffffff",
  ink: "#0f172a",
  muted: "#64748b",
  line: "#e2e8f0",
  accent: "#2563eb",
  accentSoft: "#dbeafe",
  danger: "#dc2626",
  dangerSoft: "#fef2f2",
};

export const styles = {
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 16, paddingBottom: 32 },
  title: { fontSize: 28, fontWeight: "700" as const, color: colors.ink },
  subtitle: { fontSize: 15, color: colors.muted, marginTop: 4, lineHeight: 22 },
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  hint: { fontSize: 13, color: colors.muted, lineHeight: 18 },
  errorBox: {
    backgroundColor: colors.dangerSoft,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  errorText: { color: colors.danger, fontSize: 14 },
  primaryBtn: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center" as const,
    marginTop: 8,
  },
  primaryBtnText: { color: "#fff", fontWeight: "600" as const, fontSize: 16 },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center" as const,
    marginTop: 8,
  },
  secondaryBtnText: { color: colors.ink, fontWeight: "600" as const, fontSize: 16 },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: colors.card,
    marginTop: 4,
  },
};
